home:
    path: /
    controller: App\Controller\HomeController::index

brand:
    path: /brand
    controller: App\Controller\BrandController::index

color:
    path: /color
    controller: App\Controller\ColorController::index

size:
    path: /size
    controller: App\Controller\SizeController::index

product:
    path: /product
    controller: App\Controller\ProductController::index

stock:
    path: /stock
    controller: App\Controller\StockController::index
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
