home:
    path: /admin
    controller: App\Controller\Admin\HomeController::index

brand:
    path: /admin/brand
    controller: App\Controller\Admin\BrandController::index

color:
    path: /admin/color
    controller: App\Controller\Admin\ColorController::index

size:
    path: /admin/size
    controller: App\Controller\Admin\SizeController::index

product:
    path: /admin/product
    controller: App\Controller\Admin\ProductController::index

stock:
    path: /admin/stock
    controller: App\Controller\Admin\StockController::index

accueil:
    path: /
    controller: App\Controller\AccueilController::index
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
